Repository bitfinexcom/ufx-ui, pull requests merged in 2021-06, with the labels that each got.

#45 (improvement) TickerList: showing X button if input is filled && clear input on click
  packages/core/src/components/TickerList/TickerList.Toolbar.js
Labels: PR: Improvement :dizzy:

#44 (fix) TickerList: prevent showing favorites tickers list if one is empty
  packages/core/src/components/TickerList/TickerList.js
Labels: PR: Bug Fix :bug:

#43 (improvement) TickerList: added filtering by fullnames of ccy
  packages/core/src/components/TickerList/TickerList.constants.js
  packages/core/src/components/TickerList/TickerList.js
  packages/core/src/components/TickerList/stories/TickerList.stories_data.js
Labels: PR: Improvement :dizzy:

#46 (fix) document is undefined error for ssr build in gatsby app
  packages/core/src/components/Book/Book.Toolbar.js
  packages/core/src/components/DepthChart/DepthChart.Toolbar.js
  packages/core/src/components/DepthChart/DepthChart.helpers.js
Labels: PR: Bug Fix :bug:

#48 (improvement) book/trades: add new selectors, clean up unsubscribed state
  packages/bfx-containers/src/redux/reducers/book.reducer.js
  packages/bfx-containers/src/redux/reducers/trades.reducer.js
  packages/bfx-containers/src/redux/selectors/book.selectors.js
  packages/bfx-containers/src/redux/selectors/trades.selectors.js
Labels: PR: Improvement :dizzy:

#54 (refactor) scss: replace / with math.div to make compatible with dart-sass
  packages/bfx-containers/package-lock.json
  packages/bfx-containers/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/common/styles/_mixins.scss
  packages/core/src/ufx-core.scss
  packages/example/package-lock.json
  packages/example/package.json
Labels: PR: Refactor :art:

#52 (fix): TickerList: removed margins from FontAwesome styles in Searchbar
  packages/core/src/components/TickerList/_TickerList.scss
Labels: PR: Bug Fix :bug:

#57 (improvement) notifications
  packages/core/src/components/ui/Notifications/Notifications.Message.js
  packages/core/src/components/ui/Notifications/Notifications.js
  packages/core/src/components/ui/Notifications/_Notifications.scss
Labels: PR: Improvement :dizzy:

#70 (internal) Npm audit fix
  packages/bfx-containers/package-lock.json
  packages/bfx-containers/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/eslint-config/package-lock.json
  packages/example/package-lock.json
  packages/example/package.json
  packages/storybook/package-lock.json
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: PR: Internal :house:
